#include "Common.ush"


float4 SLInvDeviceZToWorldZTransform;
Texture2D SLSceneColorTexture;

void Main(
    noperspective float2 InUV : TEXCOORD0,
    float4 Position : SV_POSITION,
    out float OutDepth : SV_DEPTH
)
{
    const uint2 PixelCoord = floor(Position.xy) * 2;
    OutDepth = 1.f / ((SLSceneColorTexture.Load(uint3(PixelCoord, 0)).a + SLInvDeviceZToWorldZTransform[3]) * SLInvDeviceZToWorldZTransform[2]);
}
